//FETCH SUBJECTS ASYNC
export const FETCH_SUBJECTS = "FETCH_SUBJECTS";
export const REQUEST_SUBJECT_SUCCESS = "REQUEST_SUBJECT_SUCCESS";
export const REQUEST_SUBJECT_ERROR = "REQUEST_SUBJECT_ERROR";
//FETCH LABS ASYNC
export const FETCH_LABS = "FETCH_LABS";
export const REQUEST_LABS_SUCCESS = "REQUEST_LABS_SUCCESS";
export const REQUEST_LABS_ERROR = "REQUEST_LABS_ERROR";
//FETCH MATERIALS ASYNC
export const FETCH_MATERIALS = "FETCH_MATERIALS";
export const REQUEST_MATERIALS_SUCCESS = "REQUEST_MATERIALS_SUCCESS";
export const REQUEST_MATERIALS_ERROR = "REQUEST_MATERIALS_ERROR";
export const CLOSE_MATERIALS_MODAL = "CLOSE_MATERIALS_MODAL";
//LOGIN&ETC CONSTANTS
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
//REGISTER&ETC CONSTANTS
export const SUBMIT_REGISTER = "SUBMIT_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
//FETCH GROUPS ASYNC
export const FETCH_GROUPS = "FETCH_GROUPS";
export const REQUEST_GROUPS_SUCCESS = "REQUEST_GROUPS_SUCCESS";
export const REQUEST_GROUPS_FAILURE = "REQUEST_GROUPS_FAILURE";
//FETCH NAMES ASYNC
export const FETCH_NAMES = "FETCH_NAMES";
export const REQUEST_NAMES_SUCCESS = "FETCH_NAMES_SUCCESS";
export const REQUEST_NAMES_FAILURE = "REQUEST_NAMES_FAILURE";
//LOGIN&REGISTRATION ALERTS
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const CLEAR = "CLEAR";